[package]
name = "redtail-agent"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository.workspace = true
authors.workspace = true
readme = "Readme.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
flytrap = "0.1.0"
redis-module = "2.0.7"
